# Generated by Django 4.0.3 on 2022-04-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfs_app', '0002_dfs_model_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfs_model_covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('patient_id', models.CharField(default='--', max_length=250)),
                ('sample_id', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=250)),
                ('site_id', models.CharField(default=0, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Dfs_model_new',
        ),
    ]
