# Generated by Django 4.0.3 on 2022-04-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfs_app', '0003_dfs_model_covid_delete_dfs_model_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfs_model_covid',
            name='timestamp',
            field=models.CharField(max_length=250),
        ),
    ]
